-- CreateEnum
CREATE TYPE "ObjectifDon" AS ENUM ('EDUCATION', 'AIDE_SOCIALE', 'FORMATION', 'AUTRES');

-- AlterTable
ALTER TABLE "Don" ADD COLUMN     "dateReception" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "faitA" TEXT,
ADD COLUMN     "objectif" "ObjectifDon" NOT NULL DEFAULT 'AUTRES',
ADD COLUMN     "objectifAutre" TEXT,
ADD COLUMN     "responsable" TEXT NOT NULL DEFAULT 'HEDJE ZINSOU RAOUL';
