-- Add new values to NatureDon enum
ALTER TYPE "NatureDon" ADD VALUE 'DES_HABITS';
ALTER TYPE "NatureDon" ADD VALUE 'DES_VIVRES';
ALTER TYPE "NatureDon" ADD VALUE 'MACHINES_A_COUDRE';
ALTER TYPE "NatureDon" ADD VALUE 'VEHICULES';
ALTER TYPE "NatureDon" ADD VALUE 'BUS_TRANSPORT';
ALTER TYPE "NatureDon" ADD VALUE 'ORDINATEURS';
ALTER TYPE "NatureDon" ADD VALUE 'MOBILIER';
ALTER TYPE "NatureDon" ADD VALUE 'JOUETS';
ALTER TYPE "NatureDon" ADD VALUE 'LIVRES';
ALTER TYPE "NatureDon" ADD VALUE 'FAUTEUILS_MEDICAUX';
ALTER TYPE "NatureDon" ADD VALUE 'BEQUILLES';
ALTER TYPE "NatureDon" ADD VALUE 'APPARTEMENT';
ALTER TYPE "NatureDon" ADD VALUE 'MAISON';
ALTER TYPE "NatureDon" ADD VALUE 'MATELAS';
ALTER TYPE "NatureDon" ADD VALUE 'IMPRIMANTES';
